from __future__ import annotations

from dataclasses import dataclass


DEFAULT_MODELS = ("qwen2_vl", "qwen3_vl", "idefics3")
CLASSIFICATION_DATASETS = ("pets", "eurosat", "flowers", "cub", "tinyimage")


@dataclass(frozen=True)
class TaskSpec:
    experiment_id: str
    dataset_name: str
    evaluator_name: str
    train_src: str
    val_src: str
    train_mode: str
    train_count: int
    val_mode: str
    val_count: int
    label_seed_count: int = 0
    train_group_size: int = 0
    val_group_size: int = 0
    shuffle_train: bool = True
    shuffle_val: bool = False


@dataclass(frozen=True)
class MethodSpec:
    method_id: str
    display_name: str
    method_name: str
    overrides: tuple[str, ...] = ()
    supported_datasets: tuple[str, ...] = ()


TASK_SPECS: dict[str, TaskSpec] = {
    "naturalbench_ret": TaskSpec(
        experiment_id="naturalbench_ret",
        dataset_name="naturalbench_ret",
        evaluator_name="naturalbench_group",
        train_src="ref-data/naturalbench_ret_train.jsonl",
        val_src="ref-data/naturalbench_ret_test.jsonl",
        train_mode="author_ref",
        train_count=0,
        val_mode="grouped",
        val_count=40,
        val_group_size=4,
    ),
    "naturalbench_vqa": TaskSpec(
        experiment_id="naturalbench_vqa",
        dataset_name="naturalbench_vqa",
        evaluator_name="raw",
        train_src="dataset/converted_from_data/naturalbench/train.jsonl",
        val_src="dataset/converted_from_data/naturalbench/train.jsonl",
        train_mode="per_label",
        train_count=20,
        val_mode="grouped",
        val_count=40,
        val_group_size=4,
    ),
    "sugarcrepe": TaskSpec(
        experiment_id="sugarcrepe",
        dataset_name="sugarcrepe",
        evaluator_name="pair",
        train_src="dataset/converted_from_data/sugarcrepe/sugarcrepe_all.jsonl",
        val_src="dataset/converted_from_data/sugarcrepe/sugarcrepe_all.jsonl",
        train_mode="per_label",
        train_count=20,
        val_mode="grouped",
        val_count=40,
        val_group_size=2,
    ),
    "pets_small": TaskSpec(
        experiment_id="pets_small",
        dataset_name="pets",
        evaluator_name="raw",
        train_src="ref-data/pets_train.json",
        val_src="dataset/converted_from_data/pets/test.json",
        train_mode="per_label",
        train_count=5,
        val_mode="per_label",
        val_count=2,
    ),
    "eurosat_small": TaskSpec(
        experiment_id="eurosat_small",
        dataset_name="eurosat",
        evaluator_name="raw",
        train_src="ref-data/eurosat_train.json",
        val_src="dataset/converted_from_data/eurosat/test.json",
        train_mode="per_label",
        train_count=10,
        val_mode="per_label",
        val_count=5,
    ),
    "flowers_small": TaskSpec(
        experiment_id="flowers_small",
        dataset_name="flowers",
        evaluator_name="raw",
        train_src="dataset/converted_from_data/flowers/train.json",
        val_src="dataset/converted_from_data/flowers/test.json",
        train_mode="per_label",
        train_count=2,
        val_mode="per_label",
        val_count=1,
    ),
    "cub_small": TaskSpec(
        experiment_id="cub_small",
        dataset_name="cub",
        evaluator_name="raw",
        train_src="dataset/converted_from_data/cub/train.json",
        val_src="dataset/converted_from_data/cub/test.json",
        train_mode="per_label",
        train_count=2,
        val_mode="per_label",
        val_count=1,
    ),
    "tinyimage_small": TaskSpec(
        experiment_id="tinyimage_small",
        dataset_name="tinyimage",
        evaluator_name="raw",
        train_src="dataset/converted_from_data/tinyimage/train.json",
        val_src="dataset/converted_from_data/tinyimage/val.json",
        train_mode="per_label",
        train_count=2,
        val_mode="per_label",
        val_count=1,
    ),
    "vizwiz": TaskSpec(
        experiment_id="vizwiz",
        dataset_name="vizwiz",
        evaluator_name="raw",
        train_src="ref-data/vizwiz_sav_train.jsonl",
        val_src="dataset/converted_from_data/vizwiz/val.jsonl",
        train_mode="author_ref",
        train_count=0,
        val_mode="per_label",
        val_count=20,
    ),
    "vlguard": TaskSpec(
        experiment_id="vlguard",
        dataset_name="vlguard",
        evaluator_name="raw",
        train_src="ref-data/vlguard_train.json",
        val_src="dataset/converted_from_data/vlguard/test.json",
        train_mode="author_ref",
        train_count=0,
        val_mode="per_label",
        val_count=20,
    ),
    "mhalubench_val_v01": TaskSpec(
        experiment_id="mhalubench_val_v01",
        dataset_name="mhalubench",
        evaluator_name="raw",
        train_src="ref-data/mahalu_train.json",
        val_src="dataset/converted_from_data/mhalubench/val_v01.json",
        train_mode="author_ref",
        train_count=0,
        val_mode="per_label",
        val_count=20,
    ),
    "mhalubench_val_v02": TaskSpec(
        experiment_id="mhalubench_val_v02",
        dataset_name="mhalubench",
        evaluator_name="raw",
        train_src="ref-data/mahalu_train.json",
        val_src="dataset/converted_from_data/mhalubench/val_v02.json",
        train_mode="author_ref",
        train_count=0,
        val_mode="per_label",
        val_count=20,
    ),
    "blink_art_style": TaskSpec(
        experiment_id="blink_art_style",
        dataset_name="blink_art_style",
        evaluator_name="raw",
        train_src="ref-data/blink_art_style_train.json",
        val_src="dataset/converted_from_data/blink/art_style_val.json",
        train_mode="author_ref",
        train_count=0,
        val_mode="per_label",
        val_count=10,
    ),
    "blink_counting": TaskSpec(
        experiment_id="blink_counting",
        dataset_name="blink_counting",
        evaluator_name="raw",
        train_src="dataset/converted_from_data/blink/counting_val.json",
        val_src="dataset/converted_from_data/blink/counting_val.json",
        train_mode="per_label",
        train_count=20,
        val_mode="per_label",
        val_count=5,
    ),
    "blink_forensic_detection": TaskSpec(
        experiment_id="blink_forensic_detection",
        dataset_name="blink_forensic_detection",
        evaluator_name="raw",
        train_src="dataset/converted_from_data/blink/forensic_detection_val.json",
        val_src="dataset/converted_from_data/blink/forensic_detection_val.json",
        train_mode="per_label",
        train_count=20,
        val_mode="per_label",
        val_count=5,
    ),
    "blink_functional_correspondence": TaskSpec(
        experiment_id="blink_functional_correspondence",
        dataset_name="blink_functional_correspondence",
        evaluator_name="raw",
        train_src="dataset/converted_from_data/blink/functional_correspondence_val.json",
        val_src="dataset/converted_from_data/blink/functional_correspondence_val.json",
        train_mode="per_label",
        train_count=20,
        val_mode="per_label",
        val_count=5,
    ),
    "blink_iq_test": TaskSpec(
        experiment_id="blink_iq_test",
        dataset_name="blink_iq_test",
        evaluator_name="raw",
        train_src="dataset/converted_from_data/blink/iq_test_val.json",
        val_src="dataset/converted_from_data/blink/iq_test_val.json",
        train_mode="per_label",
        train_count=20,
        val_mode="per_label",
        val_count=5,
    ),
    "blink_jigsaw": TaskSpec(
        experiment_id="blink_jigsaw",
        dataset_name="blink_jigsaw",
        evaluator_name="raw",
        train_src="dataset/converted_from_data/blink/jigsaw_val.json",
        val_src="dataset/converted_from_data/blink/jigsaw_val.json",
        train_mode="per_label",
        train_count=20,
        val_mode="per_label",
        val_count=10,
    ),
    "blink_multi_view_reasoning": TaskSpec(
        experiment_id="blink_multi_view_reasoning",
        dataset_name="blink_multi-view_reasoning",
        evaluator_name="raw",
        train_src="dataset/converted_from_data/blink/multi-view_reasoning_val.json",
        val_src="dataset/converted_from_data/blink/multi-view_reasoning_val.json",
        train_mode="per_label",
        train_count=20,
        val_mode="per_label",
        val_count=10,
    ),
    "blink_object_localization": TaskSpec(
        experiment_id="blink_object_localization",
        dataset_name="blink_object_localization",
        evaluator_name="raw",
        train_src="dataset/converted_from_data/blink/object_localization_val.json",
        val_src="dataset/converted_from_data/blink/object_localization_val.json",
        train_mode="per_label",
        train_count=20,
        val_mode="per_label",
        val_count=10,
    ),
    "blink_relative_depth": TaskSpec(
        experiment_id="blink_relative_depth",
        dataset_name="blink_relative_depth",
        evaluator_name="raw",
        train_src="dataset/converted_from_data/blink/relative_depth_val.json",
        val_src="dataset/converted_from_data/blink/relative_depth_val.json",
        train_mode="per_label",
        train_count=20,
        val_mode="per_label",
        val_count=10,
    ),
    "blink_relative_reflectance": TaskSpec(
        experiment_id="blink_relative_reflectance",
        dataset_name="blink_relative_reflectance",
        evaluator_name="raw",
        train_src="dataset/converted_from_data/blink/relative_reflectance_val.json",
        val_src="dataset/converted_from_data/blink/relative_reflectance_val.json",
        train_mode="per_label",
        train_count=20,
        val_mode="per_label",
        val_count=5,
    ),
    "blink_semantic_correspondence": TaskSpec(
        experiment_id="blink_semantic_correspondence",
        dataset_name="blink_semantic_correspondence",
        evaluator_name="raw",
        train_src="dataset/converted_from_data/blink/semantic_correspondence_val.json",
        val_src="dataset/converted_from_data/blink/semantic_correspondence_val.json",
        train_mode="per_label",
        train_count=20,
        val_mode="per_label",
        val_count=5,
    ),
    "blink_spatial_relation": TaskSpec(
        experiment_id="blink_spatial_relation",
        dataset_name="blink_spatial_relation",
        evaluator_name="raw",
        train_src="dataset/converted_from_data/blink/spatial_relation_val.json",
        val_src="dataset/converted_from_data/blink/spatial_relation_val.json",
        train_mode="per_label",
        train_count=20,
        val_mode="per_label",
        val_count=10,
    ),
    "blink_visual_correspondence": TaskSpec(
        experiment_id="blink_visual_correspondence",
        dataset_name="blink_visual_correspondence",
        evaluator_name="raw",
        train_src="dataset/converted_from_data/blink/visual_correspondence_val.json",
        val_src="dataset/converted_from_data/blink/visual_correspondence_val.json",
        train_mode="per_label",
        train_count=20,
        val_mode="per_label",
        val_count=5,
    ),
    "blink_visual_similarity": TaskSpec(
        experiment_id="blink_visual_similarity",
        dataset_name="blink_visual_similarity",
        evaluator_name="raw",
        train_src="dataset/converted_from_data/blink/visual_similarity_val.json",
        val_src="dataset/converted_from_data/blink/visual_similarity_val.json",
        train_mode="per_label",
        train_count=20,
        val_mode="per_label",
        val_count=10,
    ),
    "eurosat_fgvc": TaskSpec(
        experiment_id="eurosat_fgvc",
        dataset_name="eurosat",
        evaluator_name="raw",
        train_src="dataset/converted_from_data/eurosat/train.json",
        val_src="dataset/converted_from_data/eurosat/test.json",
        train_mode="per_label",
        train_count=10,
        val_mode="per_label",
        val_count=10,
        label_seed_count=10,
    ),
    "pets_fgvc": TaskSpec(
        experiment_id="pets_fgvc",
        dataset_name="pets",
        evaluator_name="raw",
        train_src="dataset/converted_from_data/pets/train.json",
        val_src="dataset/converted_from_data/pets/test.json",
        train_mode="per_label",
        train_count=5,
        val_mode="per_label",
        val_count=5,
        label_seed_count=20,
    ),
    "cub_fgvc": TaskSpec(
        experiment_id="cub_fgvc",
        dataset_name="cub",
        evaluator_name="raw",
        train_src="dataset/converted_from_data/cub/train.json",
        val_src="dataset/converted_from_data/cub/test.json",
        train_mode="per_label",
        train_count=5,
        val_mode="per_label",
        val_count=5,
        label_seed_count=20,
    ),
}


METHOD_SPECS: dict[str, MethodSpec] = {
    "zero_shot": MethodSpec("zero_shot", "Zero-shot", "zero_shot"),
    "sav": MethodSpec("sav", "SAV", "sav"),
    "whitened_ncm": MethodSpec(
        "whitened_ncm",
        "Whitened NCM",
        "whitened_ncm",
        supported_datasets=CLASSIFICATION_DATASETS,
    ),
    "ridge_probe": MethodSpec(
        "ridge_probe",
        "Ridge Probe",
        "ridge_probe",
        supported_datasets=CLASSIFICATION_DATASETS,
    ),
    "keco": MethodSpec("keco", "KeCO", "keco", supported_datasets=CLASSIFICATION_DATASETS),
    "rse": MethodSpec("rse", "RSE", "rse"),
    "rse_zscore": MethodSpec(
        "rse_zscore",
        "RSE-ZScore",
        "rse",
        overrides=(
            "method.params.selection_metric=loo_accuracy",
            "method.params.score_normalization=zscore",
        ),
    ),
    "rse_adaptive": MethodSpec(
        "rse_adaptive",
        "RSE-Adaptive",
        "rse",
        overrides=(
            "method.params.selection_metric=loo_accuracy",
            "method.params.routing_mode=adaptive",
            "method.params.adaptive_margin_quantile=0.6",
            "method.params.score_normalization=zscore",
        ),
    ),
    "stv": MethodSpec(
        "stv",
        "STV",
        "stv",
        overrides=(
            "method.params.head_selection_mode=sensitivity",
            "method.params.cluster_selection_mode=rl",
        ),
    ),
    "i2cl": MethodSpec("i2cl", "I2CL", "i2cl"),
    "mimic": MethodSpec("mimic", "MimIC", "mimic"),
    "rsev2": MethodSpec("rsev2", "RSEv2", "rsev2"),
    "rsev2_head_only": MethodSpec(
        "rsev2_head_only",
        "RSEv2-HeadOnly",
        "rsev2",
        overrides=("method.params.representation_levels=[head]",),
    ),
    "rsev2_equal_weight": MethodSpec(
        "rsev2_equal_weight",
        "RSEv2-EqualWeight",
        "rsev2",
        overrides=("method.params.component_weighting=uniform",),
    ),
    "rsev2_top1": MethodSpec(
        "rsev2_top1",
        "RSEv2-Top1",
        "rsev2",
        overrides=("method.params.component_top_k=1",),
    ),
    "rsev2_top4": MethodSpec(
        "rsev2_top4",
        "RSEv2-Top4",
        "rsev2",
        overrides=("method.params.component_top_k=4",),
    ),
    "rsev2_top8": MethodSpec(
        "rsev2_top8",
        "RSEv2-Top8",
        "rsev2",
        overrides=("method.params.component_top_k=8",),
    ),
    "rsev2_all": MethodSpec(
        "rsev2_all",
        "RSEv2-All",
        "rsev2",
        overrides=("method.params.component_top_k=0",),
    ),
}


TASK_GROUPS: dict[str, tuple[str, ...]] = {
    "all_tasks_current": (
        "naturalbench_ret",
        "naturalbench_vqa",
        "sugarcrepe",
        "pets_small",
        "eurosat_small",
        "flowers_small",
        "cub_small",
        "tinyimage_small",
        "vizwiz",
        "vlguard",
        "mhalubench_val_v01",
        "mhalubench_val_v02",
        "blink_art_style",
        "blink_counting",
        "blink_forensic_detection",
        "blink_functional_correspondence",
        "blink_iq_test",
        "blink_jigsaw",
        "blink_multi_view_reasoning",
        "blink_object_localization",
        "blink_relative_depth",
        "blink_relative_reflectance",
        "blink_semantic_correspondence",
        "blink_spatial_relation",
        "blink_visual_correspondence",
        "blink_visual_similarity",
    ),
    "fgvc_core_large": (
        "eurosat_fgvc",
        "pets_fgvc",
        "cub_fgvc",
    ),
    "fgvc_extended": (
        "eurosat_fgvc",
        "pets_fgvc",
        "cub_fgvc",
        "flowers_small",
        "tinyimage_small",
    ),
    "cross_model_core8": (
        "cub_fgvc",
        "eurosat_fgvc",
        "pets_fgvc",
        "naturalbench_vqa",
        "sugarcrepe",
        "vizwiz",
        "vlguard",
        "blink_semantic_correspondence",
    ),
    "ablation_core6": (
        "cub_fgvc",
        "eurosat_fgvc",
        "naturalbench_vqa",
        "sugarcrepe",
        "vlguard",
        "blink_semantic_correspondence",
    ),
    "efficiency_core6": (
        "cub_fgvc",
        "eurosat_fgvc",
        "naturalbench_vqa",
        "sugarcrepe",
        "vlguard",
        "blink_semantic_correspondence",
    ),
}


METHOD_GROUPS: dict[str, tuple[str, ...]] = {
    "gap_findings": ("zero_shot", "sav", "rsev2"),
    "task_peaks": ("rsev2",),
    "read_vs_write": ("zero_shot", "sav", "rsev2", "stv", "i2cl", "mimic"),
    "main_results": ("zero_shot", "sav", "rsev2"),
    "rsev2_ablation": (
        "rse",
        "rse_zscore",
        "rse_adaptive",
        "rsev2",
        "rsev2_head_only",
        "rsev2_equal_weight",
        "rsev2_top1",
        "rsev2_top4",
        "rsev2_top8",
        "rsev2_all",
    ),
    "efficiency": ("zero_shot", "sav", "rsev2", "mimic", "i2cl", "stv"),
    "fgvc_baselines": ("zero_shot", "keco", "sav", "rse", "rsev2", "stv", "i2cl", "mimic"),
    "fgvc_review_simple": ("zero_shot", "sav", "whitened_ncm", "ridge_probe", "rsev2"),
}


METHOD_ORDER = tuple(METHOD_SPECS.keys())
